### ISSUE TITLE
Version 1.0.3 not working in moodle 3.7+

### ISSUE THREAD

**Issue by mputzi** [mebis-lp/moodle-qtype_geogebra#10]
Before & after Upgrading to 1.0.3 questions of Geogebra-type are not working anymore.
On JS-console I get two different errors:

- `Error: Mismatched anonymous define() module: function(){return GGBApplet} http://requirejs.org/docs/errors.html#mismatch`
and
- `TypeError: ggbApplet.getExerciseResult is not a function` triggered by `ggbq.js:70:74`
(tested on moodle 3.7+)

**Comment by mputzi** [comment]
Version 1.0.5 ist still not working in moodle 3.7+ !
The TypeError doesn't appear any more, but the problem with require.js still persists
![Screenshot_20190710_214616](https://user-images.githubusercontent.com/5164032/60999787-40bda580-a35c-11e9-873d-72896095b262.png)

**Comment by mputzi** [comment]
After some research I think, the underlying problem causing this issue might be the anonymous "define"-Method used in deployggb.js in line 1619 [of the template](https://github.com/geogebra/geogebra/blob/master/web/src/main/resources/org/geogebra/web/resources/js/deployggb-template.js).
If that's the case, this issue will be raised every time deployggb.js is used in a platform or website that's using require.js with an anonymous define itself. This kind of error is [documented in require.js-docs](https://requirejs.org/docs/errors.html#mismatch). Since this issue probalby cannot be resolved via editing the code of the qtype-moodle-plugin, I will open a new issue report in the bugtracker of geogebra.

**Comment by nadavkav** [comment]
I also experience this

**Comment by nadavkav** [comment]
Found a solution for this:
https://help.geogebra.org/topic/recent-changes-in-geogebratube-seem-to-be-breaking-the-moodle-geogebra-question-type
And also a related report:
https://help.geogebra.org/topic/problem-with-moodle-qtype-plugin-is-not-solved
